[meta]
disable_recovery = false
max_heartbeat_interval_secs = 10
enable_scale_in_when_recovery = true
enable_automatic_parallelism_control = true

[streaming]
in_flight_barrier_nums = 10

[storage]
imm_merge_threshold = 2

[system]
barrier_interval_ms = 250
checkpoint_frequency = 5
max_concurrent_creating_streaming_jobs = 0
